version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: fairbear/android-ndk-sdk-loki
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Collect libraries
          command: cd external-libs && ./collect.sh && cd ../
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build apks
          command: ./gradlew :app:assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
